name: Deploy Exalted Sage

on:
  workflow_run:
    workflows: ["Build Exalted Sage"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: dotnet.yml
          workflow_conclusion: success
          name: Exalted-Sage
          path: build/
      - name: Upload Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USER }}
          server: ${{ secrets.SFTP_ADDR }}
          port: 2022
          local_path: "build/"
          remote_path: "/"
          sftp_only: true
          password: ${{ secrets.SFTP_PASS }}
          
          
