name: Deploy Exalted Sage

on:
  workflow_run:
    workflows: ["Build Exalted Sage"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Upload Files
        uses: sand4rt/ftp-deployer@v1.5
        with:
          sftp: true
          host: ${{ secrets.SFTP_HOST }}
          port: 23
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          localPath: "./New/bot/bin/Release/net5.0/"
          remotePath: "./"