name: Deploy Exalted Sage

on:
  workflow_run:
    workflows: ["Build Exalted Sage"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: dotnet.yml
          workflow_conclusion: success
          name: Exalted-Sage
          path: build/
      - name: Upload Files
        uses: Creepios/sftp-action@v1.0.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 2022
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          localPath: "build/"
          remotePath: "/"
          
